//
// Created by gab on 21/01/19.
//

const char* const interactionShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute vec4 attr_TexCoord;\n"
  "attribute vec3 attr_Tangent;\n"
  "attribute vec3 attr_Bitangent;\n"
  "attribute vec3 attr_Normal;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "attribute lowp vec4 attr_Color;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform vec4 u_lightProjectionS;\n"
  "uniform vec4 u_lightProjectionT;\n"
  "uniform vec4 u_lightFalloff;\n"
  "uniform vec4 u_lightProjectionQ;\n"
  "uniform lowp float u_colorModulate;\n"
  "uniform lowp float u_colorAdd;\n"
  "uniform vec4 u_lightOrigin;\n"
  "uniform vec4 u_viewOrigin;\n"
  "uniform vec4 u_bumpMatrixS;\n"
  "uniform vec4 u_bumpMatrixT;\n"
  "uniform vec4 u_diffuseMatrixS;\n"
  "uniform vec4 u_diffuseMatrixT;\n"
  "uniform vec4 u_specularMatrixS;\n"
  "uniform vec4 u_specularMatrixT;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec2 var_TexDiffuse;\n"
  "varying vec2 var_TexNormal;\n"
  "varying vec2 var_TexSpecular;\n"
  "varying vec4 var_TexLight;\n"
  "varying lowp vec4 var_Color;\n"
  "varying vec3 var_L;\n"
  "varying vec3 var_H;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\tmat3 M = mat3(attr_Tangent, attr_Bitangent, attr_Normal);\n"
  "\n"
  "\tvar_TexNormal.x = dot(u_bumpMatrixS, attr_TexCoord);\n"
  "\tvar_TexNormal.y = dot(u_bumpMatrixT, attr_TexCoord);\n"
  "\n"
  "\tvar_TexDiffuse.x = dot(u_diffuseMatrixS, attr_TexCoord);\n"
  "\tvar_TexDiffuse.y = dot(u_diffuseMatrixT, attr_TexCoord);\n"
  "\n"
  "\tvar_TexSpecular.x = dot(u_specularMatrixS, attr_TexCoord);\n"
  "\tvar_TexSpecular.y = dot(u_specularMatrixT, attr_TexCoord);\n"
  "\n"
  "\tvar_TexLight.x = dot(u_lightProjectionS, attr_Vertex);\n"
  "\tvar_TexLight.y = dot(u_lightProjectionT, attr_Vertex);\n"
  "\tvar_TexLight.z = dot(u_lightFalloff, attr_Vertex);\n"
  "\tvar_TexLight.w = dot(u_lightProjectionQ, attr_Vertex);\n"
  "\n"
  "\tvec3 L = u_lightOrigin.xyz - attr_Vertex.xyz;\n"
  "\tvec3 V = u_viewOrigin.xyz - attr_Vertex.xyz;\n"
  "\tvec3 H = normalize(L) + normalize(V);\n"
  "\n"
  "\tvar_L = L * M;\n"
  "\tvar_H = H * M;\n"
  "\n"
  "\tvar_Color = attr_Color * u_colorModulate + vec4(u_colorAdd, u_colorAdd, u_colorAdd, u_colorAdd);\n"
  "\n"
  "\tgl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const interactionShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// Option to use Half Lambert for shading\n"
  "//#define HALF_LAMBERT\n"
  "\n"
  "// In\n"
  "varying vec2 var_TexDiffuse;\n"
  "varying vec2 var_TexNormal;\n"
  "varying vec2 var_TexSpecular;\n"
  "varying vec4 var_TexLight;\n"
  "varying lowp vec4 var_Color;\n"
  "varying vec3 var_L;\n"
  "varying vec3 var_H;\n"
  "\n"
  "// Uniforms\n"
  "uniform lowp vec4 u_diffuseColor;\n"
  "uniform lowp vec4 u_specularColor;\n"
  "//uniform float u_specularExponent;\n"
  "uniform sampler2D u_fragmentMap0;\t/* u_bumpTexture */\n"
  "uniform sampler2D u_fragmentMap1;\t/* u_lightFalloffTexture */\n"
  "uniform sampler2D u_fragmentMap2;\t/* u_lightProjectionTexture */\n"
  "uniform sampler2D u_fragmentMap3;\t/* u_diffuseTexture */\n"
  "uniform sampler2D u_fragmentMap4;\t/* u_specularTexture */\n"
  "\n"
  "// Out\n"
  "// gl_FragCoord\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\tvec3 L = normalize(var_L);\n"
  "\tvec3 H = normalize(var_H);\n"
  "\tvec3 N = 2.0 * texture2D(u_fragmentMap0, var_TexNormal.st).agb - 1.0;\n"
  "\n"
  "\tfloat NdotL = clamp(dot(N, L), 0.0, 1.0);\n"
  "#if defined(HALF_LAMBERT)\n"
  "\tNdotL *= 0.5;\n"
  "\tNdotL += 0.5;\n"
  "\tNdotL = NdotL * NdotL;\n"
  "#endif\n"
  "\tfloat NdotH = clamp(dot(N, H), 0.0, 1.0);\n"
  "\n"
  "\tvec3 lightProjection = texture2DProj(u_fragmentMap2, var_TexLight.xyw).rgb;\n"
  "\tvec3 lightFalloff = texture2D(u_fragmentMap1, vec2(var_TexLight.z, 0.5)).rgb;\n"
  "\tvec3 diffuseColor = texture2D(u_fragmentMap3, var_TexDiffuse).rgb * u_diffuseColor.rgb;\n"
  "\tvec3 specularColor = 2.0 * texture2D(u_fragmentMap4, var_TexSpecular).rgb * u_specularColor.rgb;\n"
  "\n"
  "\tfloat specularFalloff = pow(NdotH, 12.0);\n // Hardcoded to try to match with original D3 look"
  "\n"
  "\tvec3 color;\n"
  "\tcolor = diffuseColor;\n"
  "\tcolor += specularFalloff * specularColor;\n"
  "\tcolor *= NdotL * lightProjection;\n"
  "\tcolor *= lightFalloff;\n"
  "\n"
  "\tgl_FragColor = vec4(color, 1.0) * var_Color;\n"
  "}\n";

const char* const interactionPhongShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute vec4 attr_TexCoord;\n"
  "attribute vec3 attr_Tangent;\n"
  "attribute vec3 attr_Bitangent;\n"
  "attribute vec3 attr_Normal;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "attribute lowp vec4 attr_Color;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform vec4 u_lightProjectionS;\n"
  "uniform vec4 u_lightProjectionT;\n"
  "uniform vec4 u_lightFalloff;\n"
  "uniform vec4 u_lightProjectionQ;\n"
  "uniform lowp float u_colorModulate;\n"
  "uniform lowp float u_colorAdd;\n"
  "uniform vec4 u_lightOrigin;\n"
  "uniform vec4 u_viewOrigin;\n"
  "uniform vec4 u_bumpMatrixS;\n"
  "uniform vec4 u_bumpMatrixT;\n"
  "uniform vec4 u_diffuseMatrixS;\n"
  "uniform vec4 u_diffuseMatrixT;\n"
  "uniform vec4 u_specularMatrixS;\n"
  "uniform vec4 u_specularMatrixT;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec2 var_TexDiffuse;\n"
  "varying vec2 var_TexNormal;\n"
  "varying vec2 var_TexSpecular;\n"
  "varying vec4 var_TexLight;\n"
  "varying lowp vec4 var_Color;\n"
  "varying vec3 var_L;\n"
  "varying vec3 var_V;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\tmat3 M = mat3(attr_Tangent, attr_Bitangent, attr_Normal);\n"
  "\n"
  "\tvar_TexNormal.x = dot(u_bumpMatrixS, attr_TexCoord);\n"
  "\tvar_TexNormal.y = dot(u_bumpMatrixT, attr_TexCoord);\n"
  "\n"
  "\tvar_TexDiffuse.x = dot(u_diffuseMatrixS, attr_TexCoord);\n"
  "\tvar_TexDiffuse.y = dot(u_diffuseMatrixT, attr_TexCoord);\n"
  "\n"
  "\tvar_TexSpecular.x = dot(u_specularMatrixS, attr_TexCoord);\n"
  "\tvar_TexSpecular.y = dot(u_specularMatrixT, attr_TexCoord);\n"
  "\n"
  "\tvar_TexLight.x = dot(u_lightProjectionS, attr_Vertex);\n"
  "\tvar_TexLight.y = dot(u_lightProjectionT, attr_Vertex);\n"
  "\tvar_TexLight.z = dot(u_lightFalloff, attr_Vertex);\n"
  "\tvar_TexLight.w = dot(u_lightProjectionQ, attr_Vertex);\n"
  "\n"
  "\tvec3 L = u_lightOrigin.xyz - attr_Vertex.xyz;\n"
  "\tvec3 V = u_viewOrigin.xyz - attr_Vertex.xyz;\n"
  "\n"
  "\tvar_L = L * M;\n"
  "\tvar_V = V * M;\n"
  "\n"
  "\tvar_Color = attr_Color * u_colorModulate + vec4(u_colorAdd, u_colorAdd, u_colorAdd, u_colorAdd);\n"
  "\n"
  "\tgl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const interactionPhongShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// Option to use Half Lambert for shading\n"
  "//#define HALF_LAMBERT\n"
  "\n"
  "// In\n"
  "varying vec2 var_TexDiffuse;\n"
  "varying vec2 var_TexNormal;\n"
  "varying vec2 var_TexSpecular;\n"
  "varying vec4 var_TexLight;\n"
  "varying lowp vec4 var_Color;\n"
  "varying vec3 var_L;\n"
  "varying vec3 var_V;\n"
  "\n"
  "// Uniforms\n"
  "uniform lowp vec4 u_diffuseColor;\n"
  "uniform lowp vec4 u_specularColor;\n"
  "uniform float u_specularExponent;\n"
  "uniform sampler2D u_fragmentMap0;\t/* u_bumpTexture */\n"
  "uniform sampler2D u_fragmentMap1;\t/* u_lightFalloffTexture */\n"
  "uniform sampler2D u_fragmentMap2;\t/* u_lightProjectionTexture */\n"
  "uniform sampler2D u_fragmentMap3;\t/* u_diffuseTexture */\n"
  "uniform sampler2D u_fragmentMap4;\t/* u_specularTexture */\n"
  "\n"
  "// Out\n"
  "// gl_FragCoord\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\n"
  "\tvec3 L = normalize(var_L);\n"
  "\tvec3 V = normalize(var_V);\n"
  "\tvec3 N = normalize(2.0 * texture2D(u_fragmentMap0, var_TexNormal.st).agb - 1.0);\n"
  "\n"
  "\tfloat NdotL = clamp(dot(N, L), 0.0, 1.0);\n"
  "#if defined(HALF_LAMBERT)\n"
  "\tNdotL *= 0.5;\n"
  "\tNdotL += 0.5;\n"
  "\tNdotL = NdotL * NdotL;\n"
  "#endif\n"
  "\n"
  "\tvec3 lightProjection = texture2DProj(u_fragmentMap2, var_TexLight.xyw).rgb;\n"
  "\tvec3 lightFalloff = texture2D(u_fragmentMap1, vec2(var_TexLight.z, 0.5)).rgb;\n"
  "\tvec3 diffuseColor = texture2D(u_fragmentMap3, var_TexDiffuse).rgb * u_diffuseColor.rgb;\n"
  "\tvec3 specularColor = 2.0 * texture2D(u_fragmentMap4, var_TexSpecular).rgb * u_specularColor.rgb;\n"
  "\n"
  "\tvec3 R = -reflect(L, N);\n"
  "\tfloat RdotV = clamp(dot(R, V), 0.0, 1.0);\n"
  "\tfloat specularFalloff = pow(RdotV, u_specularExponent);\n"
  "\n"
  "\tvec3 color;\n"
  "\tcolor = diffuseColor;\n"
  "\tcolor += specularFalloff * specularColor;\n"
  "\tcolor *= NdotL * lightProjection;\n"
  "\tcolor *= lightFalloff;\n"
  "\n"
  "\tgl_FragColor = vec4(color, 1.0) * var_Color;\n"
  "}\n";

const char* const fogShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute highp vec4 attr_Vertex;      // input Vertex Coordinates\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform vec4 u_texGen0S;         // fogPlane 0\n"
  "uniform vec4 u_texGen0T;         // fogPlane 1\n"
  "uniform vec4 u_texGen1S;         // fogPlane 3 (not 2!)\n"
  "uniform vec4 u_texGen1T;         // fogPlane 2\n"
  "\n"
  "// Out\n"
  "// gl_Position                   // output Vertex Coordinates\n"
  "varying vec2 var_TexFog;         // output Fog TexCoord\n"
  "varying vec2 var_TexFogEnter;    // output FogEnter TexCoord\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "\n"
  "  var_TexFog.x      = dot(u_texGen0S, attr_Vertex);\n"
  "  var_TexFog.y      = dot(u_texGen0T, attr_Vertex);\n"
  "\n"
  "  var_TexFogEnter.x = dot(u_texGen1S, attr_Vertex);\n"
  "  var_TexFogEnter.y = dot(u_texGen1T, attr_Vertex);\n"
  "}\n";

const char* const fogShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "varying vec2 var_TexFog;            // input Fog TexCoord\n"
  "varying vec2 var_TexFogEnter;       // input FogEnter TexCoord\n"
  "\n"
  "// Uniforms\n"
  "uniform sampler2D u_fragmentMap0;\t // Fog Image\n"
  "uniform sampler2D u_fragmentMap1;\t // Fog Enter Image\n"
  "uniform lowp vec4 u_fogColor;       // Fog Color\n"
  "\n"
  "// Out\n"
  "// gl_FragCoord                     // output Fragment color\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  gl_FragColor = texture2D( u_fragmentMap0, var_TexFog ) * texture2D( u_fragmentMap1, var_TexFogEnter ) * vec4(u_fogColor.rgb, 1.0);\n"
  "}\n";

const char* const zfillShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute vec4 attr_TexCoord;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform mat4 u_textureMatrix;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec4 var_TexDiffuse;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\tvar_TexDiffuse = u_textureMatrix * attr_TexCoord;\n"
  "\n"
  "\tgl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const zfillShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "varying vec4 var_TexDiffuse;\n"
  "\n"
  "// Uniforms\n"
  "uniform sampler2D u_fragmentMap0;\n"
  "uniform lowp float u_alphaTest;\n"
  "uniform lowp vec4 u_glColor;\n"
  "\n"
  "// Out\n"
  "// gl_FragCoord\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "    if (u_alphaTest > texture2D(u_fragmentMap0, var_TexDiffuse.xy / var_TexDiffuse.w).a) {\n"
  "        discard;\n"
  "    }\n"
  "\n"
  "\tgl_FragColor = u_glColor;\n"
  "}\n";


const char* const zfillClipShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute vec4 attr_TexCoord;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform mat4 u_textureMatrix;\n"
  "uniform vec4 u_texGen0S;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec4 var_TexDiffuse;\n"
  "varying vec2 var_TexClip;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "    var_TexClip = vec2( dot( u_texGen0S, attr_Vertex), 0 );\n"
  "\n"
  "    var_TexDiffuse = (u_textureMatrix * attr_TexCoord);\n"
  "\n"
  "\tgl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const zfillClipShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "varying vec4 var_TexDiffuse;\n"
  "varying vec2 var_TexClip;\n"
  "\n"
  "// Uniforms\n"
  "uniform sampler2D u_fragmentMap0;\n"
  "uniform sampler2D u_fragmentMap1;\n"
  "uniform lowp float u_alphaTest;\n"
  "uniform lowp vec4 u_glColor;\n"
  "\n"
  "// Out\n"
  "// gl_FragCoord\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "    if (u_alphaTest > (texture2D(u_fragmentMap0, var_TexDiffuse.xy / var_TexDiffuse.w).a * texture2D(u_fragmentMap1, var_TexClip).a) ) {\n"
  "        discard;\n"
  "    }\n"
  "\n"
  "\tgl_FragColor = u_glColor;\n"
  "}\n";

const char* const defaultSurfaceShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute lowp vec4 attr_Color;\n"
  "attribute vec4 attr_TexCoord;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform mat4 u_textureMatrix;\n"
  "uniform lowp float u_colorAdd;\n"
  "uniform lowp float u_colorModulate;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec4 var_TexCoord;\n"
  "varying lowp vec4 var_Color;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  var_TexCoord = u_textureMatrix * attr_TexCoord;\n"
  "\n"
  "  var_Color = attr_Color * u_colorModulate + vec4(u_colorAdd, u_colorAdd, u_colorAdd, u_colorAdd);\n"
  "\n"
  "  gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const diffuseCubeShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute lowp vec4 attr_Color;\n"
  "attribute vec3 attr_Normal;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform mat4 u_textureMatrix;\n"
  "uniform lowp float u_colorAdd;\n"
  "uniform lowp float u_colorModulate;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec4 var_TexCoord;\n"
  "varying lowp vec4 var_Color;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  var_TexCoord = u_textureMatrix * vec4(attr_Normal, 0.0);\n"
  "\n"
  "  var_Color = attr_Color * u_colorModulate + vec4(u_colorAdd, u_colorAdd, u_colorAdd, u_colorAdd);\n"
  "\n"
  "  gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const skyboxCubeShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute lowp vec4 attr_Color;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform mat4 u_textureMatrix;\n"
  "uniform lowp float u_colorAdd;\n"
  "uniform lowp float u_colorModulate;\n"
  "uniform vec4 u_viewOrigin;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec4 var_TexCoord;\n"
  "varying lowp vec4 var_Color;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  var_TexCoord = u_textureMatrix * (attr_Vertex - u_viewOrigin);\n"
  "  \n"
  "  var_Color = attr_Color * u_colorModulate + vec4(u_colorAdd, u_colorAdd, u_colorAdd, u_colorAdd);\n"
  "  \n"
  "  gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const reflectionCubeShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute lowp vec4 attr_Color;\n"
  "attribute vec3 attr_Normal;\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform mat4 u_modelViewMatrix;\n"
  "uniform mat4 u_textureMatrix;\n"
  "uniform lowp float u_colorAdd;\n"
  "uniform lowp float u_colorModulate;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "varying vec4 var_TexCoord;\n"
  "varying lowp vec4 var_Color;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  var_TexCoord = u_textureMatrix\n"
  "                       * reflect( normalize( u_modelViewMatrix * attr_Vertex ), \n"
  "                                   // This suppose the modelView matrix is orthogonal\n"
  "                                   // Otherwise, we should use the inverse transpose\n"
  "                                   u_modelViewMatrix * vec4(attr_Normal,0.0) ) ;\n"
  "  \n"
  "  var_Color = attr_Color * u_colorModulate + vec4(u_colorAdd, u_colorAdd, u_colorAdd, u_colorAdd);\n"
  "  \n"
  "  gl_Position = u_modelViewProjectionMatrix * attr_Vertex;\n"
  "}\n";

const char* const diffuseMapShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "uniform sampler2D u_fragmentMap0;\n"
  "uniform lowp vec4 u_glColor;\n"
  "\n"
  "varying vec4 var_TexCoord;\n"
  "varying lowp vec4 var_Color;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  gl_FragColor = texture2D(u_fragmentMap0, var_TexCoord.xy / var_TexCoord.w) * u_glColor * var_Color;\n"
  "}\n";

const char* const cubeMapShaderFP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "uniform samplerCube u_fragmentCubeMap0;\n"
  "uniform lowp vec4 u_glColor;\n"
  "\n"
  "varying vec4 var_TexCoord;\n"
  "varying lowp vec4 var_Color;\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "  gl_FragColor = textureCube(u_fragmentCubeMap0, var_TexCoord.xyz) * u_glColor * var_Color;\n"
  "}\n";

const char* const stencilShadowShaderVP =
  "#version 100\n"
  "precision mediump float;\n"
  "\n"
  "// In\n"
  "attribute highp vec4 attr_Vertex;\n"
  "\n"
  "// Uniforms\n"
  "uniform highp mat4 u_modelViewProjectionMatrix;\n"
  "uniform highp vec4 u_lightOrigin;\n"
  "\n"
  "// Out\n"
  "// gl_Position\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\tgl_Position =\n"
  "    \t    u_modelViewProjectionMatrix * (attr_Vertex.w * u_lightOrigin +\n"
  "    \t\t\t\t\t   attr_Vertex - u_lightOrigin);\n"
  "\n"
  "}\n";

const char* const stencilShadowShaderFP =
  "#version 100\n"
  "precision lowp float;\n"
  "\n"
  "// Out\n"
  "// gl_FragColor\n"
  "\n"
  "void main(void)\n"
  "{\n"
  "\tgl_FragColor = vec4(0,0,0,1.0);\n"
  "}\n";
